variable:
    add:
        # Do this in order to avoid OP from setting a value too high
        # So that the value must be >= 0 AND <= 1000
        maxProb: 1000
        maxClassCount: 100
    list:
        RowsPerPage: 8
    make:
        TicketItemType: PAPER
        Enchant: Yes

system:
    PluginVersion: 0.0.1
    VaultSupport: Yes