name: ${name}
artifactId: ${artifactId}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
 
main: ${groupId}.${artifactId}.${mainClass}
mainCommand: ${mainCommand}
database: true
softdepend: [Vault]

commands:
    ${artifactId}:
        description: Basic command.
        usage: Type /<command> help to get help.
        permission: ${artifactId}.use
        permission-message: You are not permitted to use this plugin.

permissions:
    ${artifactId}.*:
        description: Gives access to all ${name} commands.
        default: op
    ${artifactId}.admin:
        description: Gives access to all ${name} administrative commands.
        children:
            ${artifactId}.reload: true
            ${artifactId}.list: true
            ${artifactId}.use: true
            ${artifactId}.class.*: true
        default: op
    ${artifactId}.reload:
        description: Reloads the plugin.
        default: op
    ${artifactId}.list:
        description: Players with this permission can list all the prizes.
        default: op
    ${artifactId}.use:
        description: Gives access to use lottery ticket.
        default: true
    ${artifactId}.class.*:
        description: Gives access to use class X lottery ticket.
        default: true